local lang = {
    -- META
    "LLANG_NATIVE_NAME",

    -- NOTIFY TEXT
    "LNOTIFY_TEXT_HEADER",
    "LNOTIFY_TEXT_HEADER_OK",
    "LNOTIFY_TEXT_HEADER_LOST",
    "LNOTIFY_TEXT_HEADER_FAILED",
    "LNOTIFY_TEXT_ROOM_NIL",

    -- ROOMS
    "LROOM_NULL",
    "LROOM_DEFAULT",
    "LROOM_ERROR",
    "LROOM_SECRET",
    "LROOM_SUPERSECRET",
    "LROOM_ULTRASECRET",
    "LROOM_SHOP",
    "LROOM_TREASURE",
    "LROOM_SACRIFICE",
    "LROOM_LIBRARY",
    "LROOM_ARCADE",
    "LROOM_CHALLENGE",
    "LROOM_PLANETARIUM",
    "LROOM_ISAACS",
    "LROOM_BARREN",
    "LROOM_CHEST",
    "LROOM_DICE",
    "LROOM_CURSE",
    "LROOM_DEVIL",
    "LROOM_ANGEL",
    "LROOM_DUNGEON",
    "LROOM_MINIBOSS",
    "LROOM_BOSS",
    "LROOM_SECRET_EXIT",
    "LROOM_BLUE",
    "LROOM_BOSS_CHALLENGE",

    -- Configs
    "LLANG_CONFIG_ENABLED_LABEL",
    "LLANG_CONFIG_ENABLED_ON",
    "LLANG_CONFIG_ENABLED_OFF",


    "LLANG_CONFIG_GENERAL_SECTION",
    "LLANG_CONFIG_LANGUAGE",
    "LLANG_CONFIG_LANGUAGE_DESC",
    
    "LLANG_CONFIG_DEVELOPER_LABEL",
    "LLANG_CONFIG_DEBUG_MODE",
    "LLANG_CONFIG_DEBUG_MODE_DESC",

    "LLANG_CONFIG_DANGEROUS_AREA_LABEL",
    "LLANG_CONFIG_RESET_ALL_SETTINGS",
    "LLANG_CONFIG_RESET_ALL_SETTINGS_DESC",

    "LLANG_CONFIG_DOORS_SECTION",
    "LLANG_CONFIG_DOOR_REMINDERS_LABEL",

    "LLANG_CONFIG_MAP_SECTION",
    "LLANG_CONFIG_MAP_SPECIAL_ROOM_COLORMARKS_LABEL", -- "Map Special Room Colormarks"
    "LLANG_CONFIG_MAP_SPECIAL_ROOM_COLORMARKS_DESC",

    "LLANG_CONFIG_MAP_SPECIAL_ROOM_UNVISITED_LABEL", -- Unvisited Rooms
    "LLANG_CONFIG_MAP_SPECIAL_ROOM_VISITED_LABEL", -- Visited Rooms

}


print("local lang_enum = {")
for idx, name in ipairs(lang) do
    print("    " .. name .. " = " .. idx .. ",")
end

print("}")

